const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS';
const UPLOAD_FILE_FAIL = 'UPLOAD_FILE_FAIL';
const UPLOAD_FILE = 'UPLOAD_FILE';
const ON_CHANGE_TEXTAREA = 'ON_CHANGE_TEXTAREA';

export default {
    UPLOAD_FILE_SUCCESS,
    UPLOAD_FILE_FAIL,
    UPLOAD_FILE,
    ON_CHANGE_TEXTAREA,
};